### ISSUE TITLE
Why is EEGlab PREP not flagging up EEG files as "problematic" if the number of interpolated channels is > 25%?

### ISSUE THREAD

**Issue by faimai00** [VisLab/EEG-Clean-Tools#30]
Dear PREP group,

I am working with clinical EEG data and I am using the PREP pipeline as an early preprocessing step.
In some of my EEG files, a high number of channels get flagged as bad channels and get interpolated, e.g. 7 out of 21 in the example attached (see screenshot). 
However, in the PREP summary report, the error status for these files is still labelled as "good" (see screenshot).

![Screenshot 2022-04-26 at 09 42 59](https://user-images.githubusercontent.com/63585229/165943862-230702f6-879a-4770-b6dd-ce31a6e0fa39.png)

From the PREP reference paper (Bigdely-Shalmo et al., 2015) I understand that one of the criteria used to flag datasets with issues is if >25% of the channels get interpolated: 
"The criteria we currently use to flag datasets with serious issues include: [...]
Robust referencing interpolated more than 25% of the reference channels." 

I am wondering why this is not flagged up in the summary report (in the case of the file attached, 33% of the channels were interpolated)? 

Thank you for any help you might be able to provide! 

Best wishes,
Irene

**Comment by VisLab** [comment]
Flagging of the datasets as bad is not done in the implementation. We use the number of channels that are interpolated in downstream processing to look at the dataset more closely.  This could have been more clear, but it was meant to help people reading the report.  Note that the error status does not refer to bad datasets but rather than the algorithms successfully processed the data.

This could have been more clear.... Sorry.....
